### ISSUE TITLE
Random Number Generator

### ISSUE THREAD

**Issue by JHump20** [CSI-280/TheGameOfJim#10]
Create a random number generator where the user can pass in the maximum value the generator should output.

**Comment by chrisbendel** [comment]
Make sure this implementation allows for flexibility in what numbers can be generated. Allowing for max/min values, eventually you may want to have the function be overloaded to take multiple different types of params, such as a random value for a player based on level, random value for enemy, random value for attack, etc (pseudocode)

```
function rng(min: Double, max: Double, multiplier: Double) {
// return Math.rand(min, max) * multiplier
}

function rng(player: Player) {
// return Math.rand(player.getAttack, player.getAttack + level) * level;
}


function rng(enemy: Enemy) {
// return Math.rand(enemy.getAttack, enemy.getAttack + level) * level;
}
```

**Comment by PointlessVenture** [comment]
#26
