### ISSUE TITLE
Initialize the Codebase

### ISSUE THREAD

**Issue by PointlessVenture** [CSI-280/TheGameOfJim#2]
Initalize Solution Files, vcxproj Files, etc. Perhaps create file systems for orginization?

**Comment by chrisbendel** [comment]
@CSI-280/c-adventure-game someone (or multiple people) should jump on this first. If you work together, try and coordinate who will do what

**Comment by PointlessVenture** [comment]
I have done this- Elected to push to master, as this was the first step. If anyone @CSI-280/c-adventure-game  needs me to add something, i will.
