### ISSUE TITLE
Add more functional items class

### ISSUE THREAD

**Issue by phllpbll189** [CSI-280/TheGameOfJim#23]
Things that i could add to the class and probably will try with some time
- Being able to easily spawn items in rooms with the constructor
- a constructor to randomize what item it may be along with its stats(may or may not be done by 
  Wednesday)
- a constructor to make items that aren't necessarily weapons or armor (not sure if i can do it all in one class or not) I will likely use class inheritance for this

if there are any other things that you guys can think of for items please let me know!

**Comment by ikemike87** [comment]
What type of items are going to be in the game?
- Weapons
- Armor
- Consumables
- "Quest Items" for example a key

Will there be any others?

**Comment by phllpbll189** [comment]
I don't think that there will be anything else. Although, if I come up with something I'll let you know.

**Comment by phllpbll189** [comment]
Right now I have 4 child classes of an item class.
_weapons, armor, consumables, and quest items._

each of them of course have a name and description. although the only unique stats I came up with was healing for consumables, attack for weapons, and defense for armor.

I think im going to keep it this way just to get the basics all established

**Comment by PointlessVenture** [comment]
Is this done?

**Comment by phllpbll189** [comment]
yes, this is done. I forgot to close the issue.
