### ISSUE TITLE
Flexible gender when writing the story.

### ISSUE THREAD

**Issue by ikemike87** [CSI-280/TheGameOfJim#27]
Since, the player class is allowing for the player to choose their name, if we ever need to refer to the player as he or she this would depend on having a gender for the player. Also when writing the story sometimes the use of he is needed and sometimes she is needed. 

- Add gender to the player class
- Add gender option to intro
- function to return he/she, her/him, etc depending on gender. 

Let me know if you have any questions.

**Comment by PointlessVenture** [comment]
Is this done?
