### ISSUE TITLE
Create Inventory System

### ISSUE THREAD

**Issue by PointlessVenture** [CSI-280/TheGameOfJim#3]
Create an Inventory system an Item System.

**Comment by HaydenStegman** [comment]
### Inventory System Details
The player inventory is responsible for anything the player collects along the way that can be used to help them along the way. 

**Examples of possible uses of the items in the inventory are:**
- Item required to open a certain pathway or room (Ex: Key to unlock a door).
- Item can heal the player when used (Ex: Potion or Food can be consumed).
- Item can boost player damage when equipped. (A Weapon or Sword.)(Active Inventory -To Be added after regular inventory, would be the hot bar of equipped items that would affect player stats like health, damage, ect.)

**Initial Set Up Required**
- [x] Set up PlayerInventory Class
- [x] Set up Item Class
- [x] Ability to add Items to inventory
- [x] Ability to remove items from inventory
- [ ] Ability to view items in the player's inventory

**Comment by HaydenStegman** [comment]
If you have other ideas or uses for the inventory, please comment them.

**Comment by HaydenStegman** [comment]
@PointlessVenture I see you added the Vague Issue tag. I just wanted to ask what about it you thought was vague so we can clear it up.

**Comment by chrisbendel** [comment]
I think @HaydenStegman 's reply comment provides enough detail for this issue now

**Comment by PointlessVenture** [comment]
I added the Vague issue class moreso as a consideration to what was going on in other threads- keep an eye on the discussions of player/combat/enemies. The general features are as listed above, but the specifics of how those things may rely on how those things interact with the inventory system may change as those issues develop, just keep that in mind.

**Comment by PointlessVenture** [comment]
#19
