### ISSUE TITLE
Create a dialogue system 

### ISSUE THREAD

**Issue by griffinsnest** [CSI-280/TheGameOfJim#43]
If we our going to have NPCs that have access to quests and items, we're going to need some form of dialogue between them and the player. We should probably start simple with just having the player have simple responses to the npc, and maybe responses to character prompts from the npc. Really this is more set up so we can better integrate a purpose for NPCs later down the line.

**Comment by PointlessVenture** [comment]
Dialogue should be able to be implemented into the room system. Is what you're suggesting to deepen that?

**Comment by ikemike87** [comment]
I think it was more what an npc would say. If that can be done through the room system that sounds good.

**Comment by ikemike87** [comment]
closing as issue is merged
