### ISSUE TITLE
Work on Room Class(es)

### ISSUE THREAD

**Issue by PointlessVenture** [CSI-280/TheGameOfJim#5]
Create classes to simulate a basic room.

**Comment by phllpbll189** [comment]
![room problem](https://user-images.githubusercontent.com/48931506/76035292-1df58800-5f0f-11ea-8bf9-7ff73b74b55a.png)

**Comment by phllpbll189** [comment]
Something that came up in the enemy's issue was if we want to have level roadblocks for the player, I think it would be smarter to have the level tied to the room and fed into the enemy class at a later date. let me know if anyone disagrees with this.

**Comment by PointlessVenture** [comment]
Rooms have a basic scheme set up in the Rooms Branch.

**Comment by PointlessVenture** [comment]
This is mostly done, still waiting on issue #3 for it to be done in full.

**Comment by phllpbll189** [comment]
is this issue ready to be closed?

**Comment by PointlessVenture** [comment]
#21
