### ISSUE TITLE
Set up Enemy Class

### ISSUE THREAD

**Issue by PointlessVenture** [CSI-280/TheGameOfJim#7]
Create a way to store an enemy and it's data.

**Comment by phllpbll189** [comment]
**Things I want to add to the enemy class**

- [ ] enemy health

- [ ] enemy attack values (Scaling? Random? needs discussion)

- [ ] different enemy behaviors (maybe not all enemies will immediately attack in said game maybe 
       some will run or be hidden?)

- [ ] enemy might have drops (if you defeat an enemy that's using a sword, you might get that 
       sword)

- [ ] enemy should be easily named when called (Goblin, Zombie, etc)

**notes**

- We need to discuss if there will be stats in the game and if any will be applied to the enemies

- If there are stats then will "Jim" level up? Will i need to make the enemies scale to his level?

**Comment by chrisbendel** [comment]
@phllpbll189 good questions, good thing for the rest of the team to weigh in on and discuss, i like the idea of scaling enemies (maybe have some functions with multipliers/RNG for enemy stats based on Jim's stats). these are good things to think about now, and can help lead to future work (figuring out the right numbers to scale by, what stats scale, etc)

**Comment by HaydenStegman** [comment]
I would say yes to stats cause this could be an easy way of progression, making certain rooms/roadblocks require certain stats from the player. thus requiring the player to complete other rooms / beat other enemies before coming back and progressing on certain story paths.

**Comment by PointlessVenture** [comment]
I'm not sure exactly how we want to do this- i'm gonna boot a discussion up on the discord. Regardless, i want to point out that we can always add things later.

**Comment by phllpbll189** [comment]
@HaydenStegman I like the idea of making some rooms roadblocks until the player has leveled up. 
If everyone else likes the idea then we will have to talk about how we want to stagger the levels of the rooms, I will make a chart and link it to this to represent what I mean.

**Comment by phllpbll189** [comment]
![room problem](https://user-images.githubusercontent.com/48931506/76035169-cc4cfd80-5f0e-11ea-8ad3-e0b3817ae38d.png)

**Comment by phllpbll189** [comment]
I will post this in the issue regarding the rooms as well. I just think the level of the rooms is heavily tied to how I will need to make the enemies

**Comment by HaydenStegman** [comment]
Not all rooms need to require a level. This could just be a way of limiting where the player could go. those first three rooms could require no level and just be basic exploration and narration for the player, or they could give the player an item that is required for some other room (item such as a key) For example say there was a boss the player needs to beat. He may be able to walk up to the door of the boss room at the start of the game, yet Jim cant enter that room until he levels up or obtains an item. This would be a simple value check that the room would run looking at the players' stats or inventory.

**Comment by PointlessVenture** [comment]
Another option could be that Jim could walk into the boss room, but he would obviously lose, and he could respawn elsewhere. I think it makes sense for the person making a branch to be able to determine what is needed to access that branch, and how accessing something they cannot access should be handled.

**Comment by HaydenStegman** [comment]
We could make it so each room has a level (hidden from the player) and that room level could just be used in scaling the enemy levels and item spawns.

Or a middle ground of both.

A room level 10 room, for example, can require level 5 to enter, yet the room its self is level 10.

so this would be 2 separate values. Room Level and Room entrance requirement level.
Of which a room entrance requirement level can just be set to 0 if he can enter regardless.

**Comment by chrisbendel** [comment]
I like @PointlessVenture's idea, I feel like it's super common in certain genres of games to be able to fight a boss - and then get absolutely demolished. I think you guys have two options if you decide to let the boss room be accessible at any time
1. Let the player respawn and keep farming/leveling up so he can beat the boss the next time (this approach requires you don't run out of rooms for the user to farm in - which would require constantly respawning enemies or infinite numbers of rooms. This would theoretically allow Jim to level up to infinity given enough time)
2. The player dies and has to restart.

maybe you can find a happy medium between the two

The other alternative is like. @HaydenStegman is saying, have a locked door essentially that requires some condition to be met before opening it - think super mario 64 with the doors that only open when you have X number of stars, or the never ending staircase up to fight bowser for the final time. Maybe Jim has to collect N number of "special items" to fight the boss?

**Comment by chrisbendel** [comment]
One more thing - this is all really good discussion. Keep in mind - you don't have to necessarily "solve" this issue right now, but its good to have discussions about it and keep it in the back of your head when you develop the underlying system to your games. Build things out at this point to allow flexibility of either (or decide on one and stick to it), so that later on when you start implementing these features, you won't be forced to refactor and rewrite the underlying logic

**Comment by HaydenStegman** [comment]
Yea for the take one implementation just set up all the code and leave it open-ended. We just need the outline of the class and methods. Not everything needs to be fully written and working, having a baseline of a class that we can expand and tweak as we better understand what our game is would be of the most value at this stage.

**Comment by PointlessVenture** [comment]
Solved in #17
