### ISSUE TITLE
Set up basic turn-based combat system

### ISSUE THREAD

**Issue by PointlessVenture** [CSI-280/TheGameOfJim#8]
Set Up a turn based combat system. Should utilize player stats, enemies, items etc.

**Comment by collin-westgate** [comment]
**What sort of turn-based combat would you guys want?**
We could have a lot of probability-based things such as whether or not attacks miss/crit, or maybe have different attacks pokemon-style. 
We probably want to integrate some sort of weapon/armor system as well with stats and different factors.
Let me know any other ideas you guys think would be good to implement.

I'll work on integrating this with whoever works on the player (#4), enemy (#7) and inventory (#3) classes.

**Comment by HaydenStegman** [comment]
At this point, it is certain that we will be implementing stats and a weapon and armor system.
The stats will be apart of the player class and the weapons/armor will exist in the player's inventory and affect the players stats.

**Comment by PointlessVenture** [comment]
#18
