### ISSUE TITLE
Write the Intro

### ISSUE THREAD

**Issue by PointlessVenture** [CSI-280/TheGameOfJim#9]
Write a basic intro that will collect needed data about the player (name, etc.)

**Comment by noah-pattersonlabaw** [comment]
**Things for the intro to accomplish:**
- [ ] Have an intro paragraph that explains how to play the game to the player
- [ ] Get player character data from player, such as the character's name

**Notes:**
Besides player name, what is other player data we need to collect? If we are going with having player stats, are we letting the player choose their initial combat stats?

**Comment by PointlessVenture** [comment]
We're gonna need to flesh out the data from the other classes first, see #4.

**Comment by PointlessVenture** [comment]
Should be unblocked now.
